# Generated by Django 3.2.10 on 2021-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=256, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новости',
                'ordering': ('date',),
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['date'], name='news_news_date_cc8c28_idx'),
        ),
    ]
